### PR TITLE
Hotfix subpalette position for dc general

### PR DESCRIPTION
**Pull request by dmolineus**

### CODE REVIEW

**Comment by zonky2** [comment]
@dmolineus I check `dev-hotfix/subpalette-position 36ce60c` - works fine!

**Review by zonky2 — APPROVED** [review]
1+

**Comment by discordier** [comment]
@dmolineus Can we fix the PHP 8 compatibility in time or should we rather remove it from this repo again?

**Review by discordier — APPROVED** [review]
LGTM

**Comment by dmolineus** [comment]
> Can we fix the PHP 8 compatibility in time or should we rather remove it from this repo again?

It's caused by failing dev-dependencies (required my contao-community-alliance/dc-general). Therefore I'd like to keep it to be aware that it's failing and we need to update our libaries as soon as possbile (e.g. my contao-community-alliance/url-builder - btw. who is maintaining it?)

**Comment by discordier** [comment]
> It's caused by failing dev-dependencies (required my contao-community-alliance/dc-general). Therefore I'd like to keep it to be aware that it's failing and we need to update our libaries as soon as possbile (e.g. my contao-community-alliance/url-builder - btw. who is maintaining it?)

Fine with me.
For the "who is maintaining it?", that would be "us", as with almost all the other libs, I guess. :disappointed:

**Pull request merged**
